spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
# to use native (without GIT) we need active profile "native"
        native:
          search-locations: classpath:/modules-config
# to use git we need to remove profile "native" and create local repository in
# given location with using "git init"
#        git:
#          uri: file:///${user.home}/config-repo
server:
  port: 8888

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
