spring:
  application:
    name: zuul-gateway

server:
  port: 9999

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

ribbon:
  eureka:
    enabled: true

zuul:
  routes:
    eureka:
      path: /eureka/**
      service-id: eureka